baseurl = "https://metroinsight.io/"
bind = "0.0.0.0"
title = "Metro Insight"
theme = "ghostwriter"
languageCode = "en-us"
copyright = "My Name"
googleAnalytics = "UA-92429235-1"
disqusShortname = "jbkoh"

[Author]
name = "Jason Koh"
profile = "https://jbkoh.github.io/"

[Taxonomies]
tag = "tags"

[Params]
intro = true
headline = "Metro Insight"
description = "Meting pot for city knowledge"
github = "https://github.com/metroinsight"
email = "jbkoh@ucsd.edu"
opengraph = false
shareTwitter = false
shareFacebook = false
shareGooglePlus = false
shareLinkedIn = false
dateFormat = "Jan 2, 2006"

[Permalinks]
post = "/:year/:month/:day/:filename/"

# [[menu.main]]
# name = "Blog"
# url = "/"
# weight = 3

[[menu.main]]
name = "About"
url = "/page/about/"
weight = 1

[[menu.main]]
name = "Datasets"
url = "/dataset/"
weight = 3
